version: "3.9"
services:

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - c:/Users/Peter/.docker/config.json:/config.json
    command: --interval 30

  consolewriting:
    image: registry.gitlab.com/petriceko/dockerdemo:Version3
    restart: always
    depends_on:
      - watchtower
