version: "3.9"
services:

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 30

  consolewriting:
    image: registry.gitlab.com/petriceko/dockerdemo:Version3
    restart: always
    depends_on:
      - watchtower

# docker-compose build
# docker-compose up
# docker-compose up -d
# docker-compose down
# docker-compose pull consolewriting
# docker-compose images

# ak updatnem consolovku, nestaci si ju iba getnut pomocou pull, povodny image treba odstranit a docker compose nastartovat. 
# docker-compose images sa sice odstrania ale data ulozene na volume ostavaju, pokial ich explicitne vymazat nechcem
# docker-compose rm

# docker-compose restart
# docker-compose pause
# docker-compose unpause

# ak spustim docker compose detached, mozem sa nan pripojit:
# docker-compose exec consolewriting bash

# docker-compose up -d --force-recreate - treba overit, ci to vzdy negetne latest verziu docker images


